### ISSUE TITLE
Hyperparameters are not working

### ISSUE THREAD

**Issue by adrien1018** [lab-ml/app#104]
1. Currently, some of the hyperparameters are showing incorrect (rounded integer) values. GET `/api/v1/run/[id]` is returning correct types and values.
2. Hyperparameter saving is not working for all hyperparameters (no matter if it is displayed correctly), either by tweaking sliders or by manually entering values. POST `/api/v1/hyper_params/[id]` is returning 500 now.

Though these are more likely two separate issues, they both appeared today (on [app.labml.ai](https://app.labml.ai)).

The screenshot of the first issue:
<img src="https://user-images.githubusercontent.com/28895002/118061733-17428a80-b3c8-11eb-84fe-dd23859cd684.png" alt="drawing" width="80%"/>

The numbers on the Run page shows correct numbers:
<img src="https://user-images.githubusercontent.com/28895002/118061711-0a259b80-b3c8-11eb-9329-0ac3d74291e2.png" alt="drawing" width="50%"/>

**Comment by hnipun** [comment]
Thanks @adrien1018 for creating this issue. I will look into that quickly and let you know.

**Comment by hnipun** [comment]
@adrien1018 Update : Both issues are related to a refactoring that I did few days back. 

1. I fixed the first issue and now it should shows the correct values as the summary card.
2. This is related to a DB change that I made. If you could save the current run checkpoints and start a new run, hyper-parameters saving should be working fine. 

or I can do a DB change ( something I have forgotten to do). Anyway I'm working on the DB change now. Will let you know the update.

Thanks again for raising this issue.

**Comment by hnipun** [comment]
@adrien1018 I deployed a fix in DB, should be working now. Let me know if its works for you. Thanks

**Comment by adrien1018** [comment]
It works well now. Thanks!
